name: Sync fork

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  trigger:
    name: Trigger sync
    if: github.repository == 'wrwrabbit/tdesktop'
    runs-on: ubuntu-latest
    environment: Release
    
    steps:
      - name: Trigger sync
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TRIGGER  }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'cpartisans',
              repo: 'tdesktop',
              workflow_id: 'sync_action.yml',
              ref: 'master',
            });
